# Create image based on the official Node 6 image from dockerhub
FROM node:6

RUN mkdir -p /usr/src/app
VOLUME ["/usr/src/app"]

WORKDIR /usr/src/app
COPY package.json /usr/src/app
RUN npm install
COPY . /usr/src/app
EXPOSE 4200

CMD ["npm", "start"]